- 👋 Oiii! Me chamo Guilhermy 
- 👀 Tenho 16 anos
- 🌱 Estou estudando linguagem de programação 
- 😄 Pronomes: Ele/Dele
- ⚡ Fato divertido: Gnosis (Γνωσις) significa “conhecimento” em grego. Espalhar o conhecimento é fundamental!
